#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/_env"

cd $HERE/work && \
wget https://cmake.org/files/v${CMAKE_VERSION}/cmake-${CMAKE_VERSION}.${CMAKE_BUILD}.tar.gz && \
tar -xvzf cmake-${CMAKE_VERSION}.${CMAKE_BUILD}.tar.gz && \
cd cmake-${CMAKE_VERSION}.${CMAKE_BUILD} && \
./bootstrap && \
make -j`nproc` && \
sudo make install && \
sudo ldconfig && \
cmake --version

function r () {
        buildah run "$CONTAINER_ID" -- "$@"
}

if [ ! -d UERANSIM ]; then
    echo 'cloning UERANSIM repository...'
    git clone https://github.com/aligungr/UERANSIM "$HERE/work/UERANSIM" \
        --branch "v$UERANSIM_VERSION" \
        --recursive \
        --depth 1
fi

RANDIR=$HERE/work/UERANSIM && \
cd $RANDIR && \
echo 'building UERANSIM repository...' && \
make -j`nproc`


CONTAINER_ID=$(buildah from "$BASE_IMAGE")

buildah add "$CONTAINER_ID" /${RANDIR}/build /UERANSIM/build
buildah add "$CONTAINER_ID" /${RANDIR}/config /UERANSIM/config
buildah add "$CONTAINER_ID" "$HERE/assets/scripts/entrypoint" /bin/ueransim

r dnf install -y \
    iputils \
    lksctp-tools
r dnf -y clean all


buildah config \
        --entrypoint /bin/ueransim \
        --workingdir /UERANSIM/build \
        "$CONTAINER_ID"


buildah commit "$CONTAINER_ID" localhost/ueransim

podman save localhost/ueransim:latest -o /vagrant/ueransim.tar
